### ISSUE TITLE
Integrate Bower stats

### ISSUE THREAD

**Issue by rayshan** [customelements/www#166]
Hi @zenorocha, nice meeting you this week. Thanks again for coming out to the Polymer event. 

As promised this issue is a placeholder to integrate bower stats. The API isn't quite ready yet. Will ping you when it is. You can see the progress here:
https://github.com/bower/bower/issues/1164#issuecomment-40901056

Here's the WIP dashboard:
https://shan.io/bower/

**Comment by zenorocha** [comment]
Hey @rayshan,

We're planning a rewrite and we would love to have Bower's per-package stats. Is there any update on this? Are you still working in this API?

**Comment by rayshan** [comment]
Hi, yes I am. Sorry for the super long delay. Just started a new job. What timeline are you guys looking at?

**Comment by zenorocha** [comment]
No problem at all. We hope to have a new release in a month or so. Could you share your plans for the per-package API?

**Comment by zenorocha** [comment]
Hey @rayshan, any news?
