### ISSUE TITLE
Featured elements

### ISSUE THREAD

**Issue by robdodson** [customelements/www#309]
There are a lot of cool elements on customelements.io but it can be tricky to find the really useful ones. What do you guys think about a featured elements section? There are a handful of elements that I would love to promote because they fill in big gaps. For instance, [ajax-form](https://github.com/garstasio/ajax-form), solves the dilemma of submitting custom input elements. [app-router](https://github.com/erikringsmuth/app-router) is a really great project for managing the state of your application. This could start off as a curated list but maybe grow into something bigger and more interesting over time. What do you all think?

**Comment by zenorocha** [comment]
Removing this one for now...

Although this section was a good idea to have, we never really updated and curated it the way it deserved it. We can mature this idea in a different format for the future.

**Comment by robdodson** [comment]
yeah no worries. I was a total slacker here :P

**Comment by zenorocha** [comment]
Not at all, we all know how busy you're :)
