### ISSUE TITLE
Add new component - core-sessionstorage

### ISSUE THREAD

**Issue by jwayong** [customelements/www#380]
https://github.com/jwayong/core-sessionstorage

**Comment by zenorocha** [comment]
Hey @jokeyrhyme, thanks for submitting!

Since you're using Bower, now you just need to add the `web-components` keyword and remove the `private` key in your `bower.json` file, also make sure it is registered:

```sh
$ bower register <my-package-name> <git-endpoint>
```

**Comment by jokeyrhyme** [comment]
I think this might be waiting for @jwayong 's attention...

**Comment by zenorocha** [comment]
Oops!

**Comment by jwayong** [comment]
Hi Zeno, I have registered the package core-sessionstorage

$ bower info core-sessionstorage

Thanks,
Jan

**Comment by zenorocha** [comment]
Still missing the `web-components` keyword...

**Comment by jwayong** [comment]
Oops, sorry. I've added it just now. Thanks...
