### ISSUE TITLE
Add new component - x-spotify

### ISSUE THREAD

**Issue by ayhankuru** [customelements/www#431]
https://github.com/ayhankuru/x-spotify

**Comment by addyosmani** [comment]
Fwiw, http://cobaimelan.github.io/x-spotify/ appears broken atm

**Comment by ayhankuru** [comment]
@addyosmani  thanks for this, fixed :+1:

**Comment by zenorocha** [comment]
Hey @ayhankuru, thanks for submitting!

Since you're using Bower and already added the `web-components` keyword in your `bower.json` file, now you just need to register it:

```sh
$ bower register <my-package-name> <git-endpoint>
```

**Comment by zenorocha** [comment]
https://customelements.io/?q=x-spotify
