### ISSUE TITLE
Add new component - HTML-GL

### ISSUE THREAD

**Issue by PixelsCommander** [customelements/www#456]
https://github.com/PixelsCommander/HTML-GL

60 FPS and amazing effects by rendering HTML/CSS in WebGL, framework agnostic

HTML GL solves "the slow DOM problem" by creating WebGL representations of DOM elements and hiding actual DOM after. As a result you still work with HTML/CSS as you are common to, but DOM elements are just facades to their WebGL represenations. These GPU accelerated textures are very effective from resources consuming perspective and are very cheap to transform or animate.

DEMO - http://pixelscommander.com/polygon/htmlgl/demo/filters.html#.VQcIY2R4qUc

**Comment by zenorocha** [comment]
Crazy stuff!

Hey @jokeyrhyme, thanks for submitting!

Since you're using Bower, now you just need to add the `web-components` keyword in your `bower.json` file and make sure it is registered:

```sh
$ bower register <my-package-name> <git-endpoint>
```

**Comment by zenorocha** [comment]
https://github.com/PixelsCommander/HTML-GL/pull/55
