### ISSUE TITLE
Add new component - polymer-elements

### ISSUE THREAD

**Issue by chuycepeda** [customelements/www#463]
https://github.com/chuycepeda/polymer-elements/tree/master/my_elements/d3asterplot-elementhttps://github.com/chuycepeda/polymer-elements

**Comment by zenorocha** [comment]
Hey @chuycepeda, thanks for submitting!

Since you're using Bower, now you just need to add the `web-components` keyword in your `bower.json` file and make sure it is registered:

```sh
$ bower register <my-package-name> <git-endpoint>
```
