### ISSUE TITLE
Add new component - mygod-image

### ISSUE THREAD

**Issue by Mygod** [customelements/www#467]
https://github.com/Mygod/mygod-image

**Comment by zenorocha** [comment]
Hey @Mygod, thanks for submitting!

Since you're using Bower and already added the `web-components` keyword in your `bower.json` file, now you just need to register it:

```sh
$ bower register <my-package-name> <git-endpoint>
```

**Comment by Mygod** [comment]
Done. (I think)

**Comment by zenorocha** [comment]
https://customelements.io/?q=mygod-image :D
