### ISSUE TITLE
Add new component - lorempixel

### ISSUE THREAD

**Issue by derekshull** [customelements/www#471]
https://github.com/derekshull/lorempixel

A Polymer web component to serve up lorempixel.com placeholder images.

**Comment by zenorocha** [comment]
Hey @derekshull, thanks for submitting!

Since you're using Bower, now you just need to add the `web-components` keyword in a `bower.json` file and make sure it is registered:

```sh
$ bower register <my-package-name> <git-endpoint>
```

**Comment by derekshull** [comment]
I actually have the folder named bower components but don't currently have
it on bower.  I will get it done though.  After it's registered will it
automatically be included?

On Sun, May 3, 2015 at 10:56 AM, Zeno Rocha <notifications@github.com>
wrote:

> Hey @derekshull <https://github.com/derekshull>, thanks for submitting!
>
> Since you're using Bower, now you just need to add the web-components
> keyword in a bower.json file and make sure it is registered:
>
> $ bower register <my-package-name> <git-endpoint>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/webcomponents/customelements.io/issues/471#issuecomment-98497220>
> .
>



-- 
Matt Shull
FEWD & Angular Mentor @ Thinkful.com <http://thinkful.com/>

**Comment by zenorocha** [comment]
Yep.

**Comment by derekshull** [comment]
Awesome, thanks!

On Tue, May 5, 2015 at 11:43 AM, Zeno Rocha <notifications@github.com>
wrote:

> Yep.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/customelements/www/issues/471#issuecomment-99135835>.
>



-- 
Matt Shull
FEWD & Angular Mentor @ Thinkful.com <http://thinkful.com/>
