### ISSUE TITLE
Add new component - lp-input

### ISSUE THREAD

**Issue by horacioibrahim** [customelements/www#474]
https://github.com/horacioibrahim/lp-input

**Comment by zenorocha** [comment]
Hey @horacioibrahim, thanks for submitting!

Since you're using Bower and already added the `web-components` keyword in your `bower.json` file, now you just need to register it:

```sh
$ bower register <my-package-name> <git-endpoint>
```

**Comment by horacioibrahim** [comment]
Olá Zeno! Obrigado!
