### ISSUE TITLE
Feature Request: Star project straight from Custom Elements.

### ISSUE THREAD

**Issue by Link2Twenty** [customelements/www#483]
It's pretty easy to make a star button, and it might be nice to be able to star directly so people know it's important, or at least helps discovery.

http://ghbtns.com/github-btn.html?user=[username]&repo=[repository]&type=watch

**Comment by zenorocha** [comment]
Thanks for the suggestion @Link2Twenty, Unfortunately, that would require an authentication layer which isn't necessary right now.

https://developer.github.com/v3/activity/starring/#star-a-repository
