### ISSUE TITLE
Browsing web components gone?

### ISSUE THREAD

**Issue by arekkas** [customelements/www#484]
Is it just me or is an overview of all registered web components missing in the new version? It would be very useful to have a browse functionality, so you can find new web components and get inspired.

**Comment by zenorocha** [comment]
Yep, the only difference is that now you have to enter a specific search query. A browse functionality is not a bad idea at all @arekkas.

**Comment by arekkas** [comment]
And it would be very important to have the same sorting possibilities as on the front page:

- order by popularity
- order by recently updated
- order by recently added

**Comment by arekkas** [comment]
For now it is of course possible to use the wildcard `*` for looking up all components, but it is not very user friendly, I had to take a look at the source first ;)

**Comment by keppelen** [comment]
Yes, our idea and create `{ q: tags }` and do research only by that tag. But for that we need to change noss fetch already have these values ​​to be entered into the search for ES . The wildcard is really not very good use.

**Comment by zenorocha** [comment]
Here's another feedback: https://twitter.com/Mouse0270/status/618121876347461632

I guess we should bring that kind of visualization back...

**Comment by mouse0270** [comment]
@zenorocha at least I am not the only one who thought this. It seems like an odd feature to be missing especially since it sounds likes it existed before.

**Comment by MeTaNoV** [comment]
+1 bring back a list of all available component! :)

**Comment by BLamy** [comment]
Seems like a pretty core feature for a catalogue. Ideally, an infinite scroll for the homepage would be nice.

**Comment by LoveAndHappiness** [comment]
+1 because I would like to look through the most popular ones.

**Comment by zenorocha** [comment]
I'm happy to announce that we finally shipped that feature!

I. We changed the link below the search input:

<img width="472" alt="screen shot 2016-01-07 at 10 27 19 pm" src="https://cloud.githubusercontent.com/assets/398893/12191834/0442c06e-b58e-11e5-8203-6d32d9065659.png">

II. We added a link in the end of each section:

<img width="393" alt="screen shot 2016-01-07 at 10 27 28 pm" src="https://cloud.githubusercontent.com/assets/398893/12191839/0b648b0c-b58e-11e5-97e5-1068fc9faaee.png">

III. We added the same same sorting possibilities as on the front page:

<img width="221" alt="screen shot 2016-01-07 at 10 27 48 pm" src="https://cloud.githubusercontent.com/assets/398893/12191842/11cb9a3a-b58e-11e5-9c26-6d9cf9557215.png">

**Comment by zenorocha** [comment]
Sorry for taking so long to ship this!

There's a bunch of other improvements still need to be made and I'll be more than happy to hear your thoughts on it. 

Happy browsing ;)

**Comment by BLamy** [comment]
:tada:
