### ISSUE TITLE
It seems like the site is not getting updated.

### ISSUE THREAD

**Issue by chris-l** [customelements/www#485]
I created an element 2 days ago but is not on customelements (is on bower and has the web-components keyword). Also, can't see new updates to elements. So, it seems like the site got stuck some days ago. Something's wrong?

**Comment by keppelen** [comment]
Hi @chris-l 
Your elements is http://search.customelements.io/?q=chris-l ?

Yes,  we offline, because problem in heroku. But we have not problem on future

**Comment by chris-l** [comment]
Yes, that list has 2 of the 3 elements that I have created. (it is missing the one I recently created)
Ok, then I'll just wait. Thanks!

**Comment by grvcoelho** [comment]
I have the same problem!

I've published two projects to bower with the *web-components* tag, but my elements are not in the search.

These are the elements: https://github.com/grvcoelho/super-presentation and https://github.com/grvcoelho/paper-share-buttons

**Comment by keppelen** [comment]
We have problem in [fetch](https://github.com/customelements/fetch), but we are working on it

**Comment by zenorocha** [comment]
Hey @grvcoelho,

This problem was fixed at: https://github.com/customelements/fetch/commit/2106c175d91d621e87bb4bcced1af66b848cda49

You can now find your elements at: https://customelements.io/search/grvcoelho
