### ISSUE TITLE
Filter on components that use polymer 1.0

### ISSUE THREAD

**Issue by nojaf** [customelements/www#488]
It would be nice to view on the website if the component uses polymer 1.0 or not.

**Comment by zenorocha** [comment]
Yep, that's on the roadmap.

Duplicated from #486

**Comment by zenorocha** [comment]
FYI first part of this has been done. We're discussing the second part now. https://github.com/customelements/api/issues/20

**Comment by nojaf** [comment]
Thanks for letting me know
