### ISSUE TITLE
Search next page routing

### ISSUE THREAD

**Issue by Link2Twenty** [customelements/www#495]
If you search and have the order set to something other than default you can't go to the next page.

https://customelements.io/search/polymer?s=pushed_at:desc
press next page and you get
https://customelements.io/search/polymer?page=2
what you want is
https://customelements.io/search/polymer?s=pushed_at:desc&page=2
this does work when typed in.

**Comment by zenorocha** [comment]
Hey @Link2Twenty, sorry for taking so long to reply. @keppelen can you check this out?

**Comment by keppelen** [comment]
Yes, this weekend i work in bugfix

**Comment by zenorocha** [comment]
lol

**Comment by keppelen** [comment]
Hi @Link2Twenty  and @zenorocha you can test? Please?

**Comment by zenorocha** [comment]
Works perfectly! Thanks @keppelen ;D
