### ISSUE TITLE
Filter repositories by keywords

### ISSUE THREAD

**Issue by zenorocha** [customelements/www#504]
We're now fetching keywords from bower and npm [1] and this can be very useful when searching.

For example, a users can search for `carousel` and filter results that contains the `polymer` keyword.

[1] https://api.customelements.io/repos/robdodson

**Comment by zenorocha** [comment]
Here's a UI inspiration for that:

![materialup](https://cloud.githubusercontent.com/assets/398893/9209578/2a6ebbf8-402c-11e5-9eae-5a40853bdcce.gif)

**Comment by Link2Twenty** [comment]
Maybe incorporated with this could be filter by dependencies

**Comment by klarkc** [comment]
Just to let you know, I am working on something now, I will keep you guys informed.
