### ISSUE TITLE
Can't show more than 15 elements even if I got over 15 hits in search

### ISSUE THREAD

**Issue by whiterockerart** [customelements/www#510]
If I'm searching for "select" and I will get 39 results for the word, 15 of these will be shown and I can play around with the "Sort by" list. In the end, there will be at least 15 of these that I will never be able to see, to validate and maybe even save some crucial work in my own projects.

You have to show all the results!

Fix it!

**Comment by zenorocha** [comment]
Thanks for reporting, seems like pagination wasn't triggered. @keppelen can you check this?

**Comment by keppelen** [comment]
@whiterockerart Thank you reporting => https://customelements.io/search/select
