### ISSUE TITLE
Outdated bower package name

### ISSUE THREAD

**Issue by tomalec** [customelements/www#514]
At [Juicy/juicy-html](http://github.com/Juicy/juicy-html) we have changed the bower package name some time ago, but at https://customelements.io/Juicy/juicy-html/ there is still old one. Is there anything we should do, or is it a bug?
> `bower i x-html -S`

**Comment by zenorocha** [comment]
Hey @tomalec,

Sorry for taking so long to answer this. The reason is because Bower has not updated it.

See: http://bower.herokuapp.com/packages/x-html

I believe you need to remove the package from there and register again. Once you do that, let me know so I can remove the old package from CE.io.

**Comment by zenorocha** [comment]
http://bower.io/docs/creating-packages/#unregister
