### ISSUE TITLE
Website not collecting new projects

### ISSUE THREAD

**Issue by ceolter** [customelements/www#515]
Hi, I've released a project including "web-components" in the bower.json, but it is not appearing in the catalogue.

```
  "keywords": [
    "web-components",
```

Is your process for pulling projects in working? Or have I done something wrong?

The project I'm working on is:
https://github.com/ceolter/ag-grid

Thanks.

**Comment by MartinsThiago** [comment]
+1 I'm having exactly the same problem. some days ago other project of mine got to be shown with no problems. This one, the only problem I would suspect is that my bower id is not exact the same of repository name... any way I think it should work  

my project is https://github.com/MartinsThiago/easy-router

**Comment by ceolter** [comment]
is anybody actively maintaining this project???

**Comment by zenorocha** [comment]
Yes there is @ceolter, @keppelen could you check? I'm swamped with clipboard.js

**Comment by ceolter** [comment]
sorry - i feel bad now :) thanks for the response. i appreciate everyone has their day jobs to do. thanks.

**Comment by MartinsThiago** [comment]
I also checked bower registry and I could find my project and @ceolter's project too, probably a service of customelements team is the one with problem

**Comment by MartinsThiago** [comment]
I couldn't check yet customelements is fetching from npm packages

**Comment by atotic** [comment]
Same here, my project is not showing up:

bower info lazy-pages
bower cached        git://github.com/atotic/lazy-pages.git#0.8.1
bower validate      0.8.1 against git://github.com/atotic/lazy-pages.git#*
  keywords: [
    'web-components',
    'polymer',
    'container'
  ],

**Comment by Link2Twenty** [comment]
Looks like fetch starting having issues 14 days ago. Though doesn't look like it was changed that recently.

**Comment by MartinsThiago** [comment]
Until now and no news, my project was not fetched yet :cry:

**Comment by zenorocha** [comment]
Error detected. One repository was published to npm but didn't had a package.json file. That caused an error on the fetch service.

**Comment by zenorocha** [comment]
https://customelements.io/ceolter/ag-grid
https://customelements.io/atotic/lazy-pages
https://customelements.io/MartinsThiago/easy-router

**Comment by zenorocha** [comment]
Again, sorry about the delay on fixing it. This has been a completely crazy week for me.

**Comment by ceolter** [comment]
My ag-Grid project is there now. Thank you :)

No worries on taking a while, I fully appreciate the open source nature of
the service.


On 3 October 2015 at 22:43, Zeno Rocha <notifications@github.com> wrote:

> Again, sorry about the delay on fixing it. This has been a completely
> crazy week for me.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/customelements/www/issues/515#issuecomment-145293052>.
>



-- 
-- 

The information transmitted is intended only for the person or entity to
which it is addressed and may contain confidential and/or privileged
material. Statements and opinions expressed in this e-mail may not
represent those of the sender. Any review, retransmission, dissemination or
other use of, or taking of any action in reliance upon, this information by
persons or entities other than the intended recipient is prohibited. If you
received this in error, please contact the sender immediately and delete
the material from any computer.

**Comment by MartinsThiago** [comment]
:D nice Zeno o/

ps: Valew, tu é fera...
