### ISSUE TITLE
Deletion delay for a component

### ISSUE THREAD

**Issue by padewitte** [customelements/www#517]
I updated my web component yesterday and remove all tags. This component is deprecated and i wanted it to not appear in customelment.io. I read the fetc code and i could not see any deletion. How it works ? Should i make a PR to mark this bower project as exclude ?

The project is https://github.com/MyScriptWebComponents/myscript-math

**Comment by zenorocha** [comment]
Done! Deletions are still manually made.

Sorry for taking so long @padewitte.

**Comment by padewitte** [comment]
thanks a lot

**Comment by zenorocha** [comment]
Thanks! Could you please unregister from Bower so we can make sure it will not be added again? http://bower.io/docs/creating-packages/#unregister

**Comment by padewitte** [comment]
Done for all of them

**Comment by zenorocha** [comment]
Done for all: https://customelements.io/MyScript/

**Comment by padewitte** [comment]
Thanks a lot !

**Comment by mkazlauskas** [comment]
Hello, please remove these elements:
- https://customelements.io/firmfirm/jwt-decode-element/
- https://customelements.io/firmfirm/idlejs-element/

Thanks!

**Comment by zenorocha** [comment]
Done @mkazlauskas!

**Comment by mkazlauskas** [comment]
Thanks @zenorocha ! One more please https://customelements.io/firmfirm/promise-to-retry/ - no longer a webcomponent

**Comment by zenorocha** [comment]
done
