### ISSUE TITLE
Possible XSS injection

### ISSUE THREAD

**Issue by fiws** [customelements/www#522]
https://customelements.io/rnicholus/file-input/
Nothing more to say I think.

![image](https://cloud.githubusercontent.com/assets/3409958/12886387/0b3a4066-ce6d-11e5-9ada-cd9c78027312.png)

**Comment by mkautzmann** [comment]
It looks like the description (maybe other components too?) is not being properly escaped. I'm taking a look.

**Comment by zenorocha** [comment]
Fixed thanks to @mkautzmann ;D
