### ISSUE TITLE
Can't find elements with keywords defined in package.json

### ISSUE THREAD

**Issue by lastmjs** [customelements/www#527]
Is it true that elements with only a package.json aren't being found even if the keyword: ['web-components'] is added? I put an element into the wild on npm a few weeks ago and it hasn't showed up yet, and also see this discussion: https://github.com/webcomponents/webcomponents.github.io/issues/322

**Comment by zenorocha** [comment]
That's not true. CustomElements.io fetches both npm and bower packages that contains the `web-components` keyword. 

The reason why your package wasn't showing is not related to this.

Problem fixed: https://customelements.io/lastmjs ;)
