### ISSUE TITLE
recently published packages not appearing on the list

### ISSUE THREAD

**Issue by christophe-g** [customelements/www#531]
Hello, 
The list seems to ignore recently created and published packages since a few days.
C.

**Comment by ruud** [comment]
I have the same problem !!
I added the keyword "web-components" and published it as a bower package (as described)

**Comment by zenorocha** [comment]
Yes, that's a known problem. Turns out bower just removed the only way of fetching packages by keywords. There's no more https://bower-component-list.herokuapp.com/keyword/web-components. They deleted the heroku app and github repo.

I'm looking into alternatives to fix that problem.

**Comment by ruud** [comment]
Looking forward to your findings! Is there a temporary solution in the meantime?

**Comment by zenorocha** [comment]
Ok, so the temporary fix is now live.

I was able to set up a new Heroku instance using that same source code: http://bowerwebcomponents.herokuapp.com/keyword/web-components

Let's see how this will work out during the week.

**Comment by ruud** [comment]
I see new web-components appearing, but I am wondering why mine is not picked-up yet: https://github.com/ruud/responsive-iframe-element

**Comment by zenorocha** [comment]
It is now https://customelements.io/ruud/responsive-iframe-element/ ;)

**Comment by ruud** [comment]
thanks :)

**Comment by gustafnk** [comment]
My repo is not being picked up either :( https://github.com/gustafnk/h-include

Changed the package.json and bower.json approximately eight hours ago.

No rush, but it would be nice to be in the list :)

**Comment by gustafnk** [comment]
It's registered know, thanks! 👍

**Comment by zenorocha** [comment]
Awesome ;)

**Comment by prushforth** [comment]
Hello,
Me too! My project is [here,](https://github.com/Maps4HTML/Web-Map-Custom-Element) but I can't figure out why its not showing up on customelements.io .  How often will it be scanned for updates ?  I would like to see how it looks on that web site and fix what I don't like.  Also, how does customelements.io figure out what the install command line should be?  Mine should be bower install web-map... thanks!

**Comment by zenorocha** [comment]
For the reasons described above, it takes couple hours for packages to be fetched from bower. You can register them on npm as well if you want to speed up the process.

Install commands are fetched from the bower.json file.

**Comment by prushforth** [comment]
OK, I will have some patience, but I changed the bower.json file 7 hours ago to include the "web-components" keyword.  I guess it only looks at the bower.json in the master branch?  And it uses the "name": "web-map" property for the install command, perhaps?  I have looked at a few other people's bower.json files and I haven't seen another place for the installation info.  Thanks sorry to bug you.
