### ISSUE TITLE
making sure homepage button is appearing

### ISSUE THREAD

**Issue by christophe-g** [customelements/www#532]
Thanks a lot for customelment.io - quite handy.

I am not sure how to make sure that a `homepage` link button (next to the `github` one) is appearing for registered components. It is working for some of my packages - but not for all - and I am not sure what makes the difference. 

Cheers!

**Comment by zenorocha** [comment]
Hey @christophe-g, we fetch that link from your GitHub repository. 

<img width="998" alt="screen shot 2016-07-01 at 8 28 34 am" src="https://cloud.githubusercontent.com/assets/398893/16526366/d27f0e0e-3f65-11e6-8836-f1722ca811e4.png">
