### ISSUE TITLE
Cant access the website

### ISSUE THREAD

**Issue by AbhayKD** [customelements/www#533]
This seems a bit odd but when i'm accessing customelements.io , it is showing error 500 to me. the page opens but nothing is loading up. Please look into the issue. Thanks

**Comment by iSuslov** [comment]
+1

**Comment by L-u-k-e** [comment]
+1

**Comment by SPAHI4** [comment]
+1

**Comment by zenorocha** [comment]
It's back again https://customelements.io ;)

**Comment by zenorocha** [comment]
Thanks for reporting everybody and sorry for the inconvenience.
