### ISSUE TITLE
Bower package not showing up

### ISSUE THREAD

**Issue by chrismbeckett** [customelements/www#537]
I recently published a Polymer-based web component to Bower named 'oxygen-language'. The 'web-components' keyword is included in my bower.json file, but the element is not showing up on the site.

**Comment by dhrytsenko** [comment]
Hi @chrismbeckett ! I have the same problem... Perhaps they stop to grab a new components for this site to use [new webcomponents website](https://www.webcomponents.org) instead

**Comment by chrismbeckett** [comment]
Yeah, I am using the new site now.
