### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by matthewp** [customelements/www#540]
Not sure if this project is still being maintained. If so, it's down:

![screen shot 2017-01-25 at 1 38 04 pm](https://cloud.githubusercontent.com/assets/361671/22303959/87729e0c-e303-11e6-8a7b-4bbcf2e6ceeb.png)

**Comment by zenorocha** [comment]
It's up again, sorry about that.

**Comment by matthewp** [comment]
No worries, thanks!
